title: Ruomin Huang (黄若民)
logo: /assets/img/logo.jpg
blank_title: true
favicon: true
description: "A graduate student at USTC DIAG Group, interested in machine learning theory and algorithmic problems of machine learning."
show_downloads: false
google_analytics: UA-108144808-1
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

sidebar:
  - name: Home
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M4 0h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm5.5 1.5v2a1 1 0 0 0 1 1h2l-3-3z"/></g></svg>
    link: ./
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: "mailto: hrm@mail.ustc.edu.cn"
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?hl=en&user=YjthT-kAAAAJ
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: /blogs
  - name: Friends
    icon: <i class="fa-solid fa-address-book"></i>
    link: /friends